program: runner.py
method: bayes
metric:
  goal: maximize
  name: return
parameters:
  train_steps_per_env_step:
    max: 4
    min: 1
    distribution: int_uniform
  polyak_tau:
    max: 0.01
    min: 0.0001
    distribution: uniform
  batch_size:
    max: 256
    min: 16
    distribution: int_uniform
  burn_in:
    max: 20000
    min: 50
    distribution: int_uniform
  gamma:
    max: 0.999
    min: 0.8
    distribution: uniform
  lr_pi:
    max: 0.003
    min: 0.0001
    distribution: uniform
  lr_q:
    max: 0.003
    min: 0.0001
    distribution: uniform
  lr_a:
    max: 0.003
    min: 0.0001
    distribution: uniform
  actor_weight_initialisation:
    values:
      - default
      - He
      - xavier_normal
    distribution: categorical
  critic_weight_initialisation:
    values:
      - default
      - He
      - xavier_normal
    distribution: categorical
  pi_hidden_size:
    max: 128
    min: 16
    distribution: int_uniform
  q_hidden_size:
    max: 128
    min: 16
    distribution: int_uniform
  alpha:
    max: 10.0
    min: 0.1
    distribution: uniform
  reward_scale:
    max: 1
    min: 0.01
    distribution: uniform
